#!/bin/bash
# Ce script affiche la categorie d'un athlete selon son annee de naissance
USAGE="Usage : categorie param1"
if [ "$#" == "0" -o "$1" = "-h" ]; then
  echo "$USAGE"
else
  if [ $1 -le 1976 ]; then
    echo -n "master";
  elif [[ $1 -le 1993 && $1 -ge 1977 ]]; then
    echo -n "senior"; 
  elif [[ $1 -le 1996 && $1 -ge 1992 ]]; then
   echo -n "espoir";
  elif [[ $1 -le 1998 && $1 -ge 1997 ]]; then
   echo -n "junior";
  elif [[ $1 -le 2000 && $1 -ge 1999 ]]; then
   echo -n "cadet";
  elif [[ $1 -le 2002 && $1 -ge 2001 ]]; then
    echo -n "minime";
  elif [[ $1 -le 2004 && $1 -ge 2003 ]]; then
    echo -n "benjamin";
  elif [[ $1 -le 2006 && $1 -ge 2005 ]]; then
    echo -n "poussin";
  elif [[ $1 -le 2009 && $1 -ge 2007 ]]; then
    echo -n "membre de l'Ecole d'Athletisme";
  elif [[ $1 -ge 2010 ]]; then
    echo -n "baby Athle";
  else
    echo -n "Valeur invalide";
  fi
fi
